Repository rdkcentral/Lightning-UI-Components, pull requests merged in 2023-03, with the labels that each got.

#121 test(TextBox): restore skipped test
  packages/@lightningjs/ui-components/src/components/InlineContent/InlineContent.test.js
  packages/@lightningjs/ui-components/src/components/TextBox/TextBox.test.js
Labels: tests

#137 docs: add repository field to display in npm docs
  package.json
  packages/@lightningjs/ui-components-test-utils/package.json
  packages/@lightningjs/ui-components-theme-base/package.json
  packages/@lightningjs/ui-components/package.json
Labels: documentation

#127 fix(Tooltip): fixed args url issue by adding sharedargactions
  packages/@lightningjs/ui-components/src/components/Tooltip/Tooltip.stories.js
Labels: bug

#130 fix(Storybook): changes check for instance of Element
  packages/apps/lightning-ui-docs/.storybook/addons/decorators/withLightning.js
Labels: bug

#134 fix(ListItemPicker): fix selection reset when switching modes
  packages/@lightningjs/ui-components/src/components/ListItem/ListItemPicker.js
  packages/@lightningjs/ui-components/src/components/ListItem/ListItemPicker.test.js
Labels: bug

#141 test: update config to not print coverage table in terminal
  jest.config.js
  packages/@lightningjs/ui-components/jest.config.mjs
Labels: tests

#147 test(Row): adds commented out test back
  packages/@lightningjs/ui-components/src/components/Row/Row.js
  packages/@lightningjs/ui-components/src/components/Row/Row.test.js
Labels: tests

#138 ci: workflow optimizations
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: pipeline

#131 fix(withLayout): adds check for positive numbers
  packages/@lightningjs/ui-components/src/mixins/withLayout/index.js
  packages/@lightningjs/ui-components/src/mixins/withLayout/withLayout.mdx
  packages/@lightningjs/ui-components/src/mixins/withLayout/withLayout.stories.js
  packages/@lightningjs/ui-components/src/mixins/withLayout/withLayout.test.js
Labels: bug

#157 test(NavigationManager): adds back skipped test for lastIndexScroll
  packages/@lightningjs/ui-components/src/components/NavigationManager/NavigationManager.test.js
Labels: tests

#146 fix(ThemingTokens): emitted signal to fix spacing issue in misc section
  packages/@lightningjs/ui-components/src/docs/ThemingFoundations.stories.js
Labels: bug

#142 fix(Input): update listening control in disabled mode
  packages/@lightningjs/ui-components/src/components/Input/Input.js
  packages/@lightningjs/ui-components/src/components/Input/Input.mdx
  packages/@lightningjs/ui-components/src/components/Input/Input.stories.js
Labels: bug

#152 fix(NavigationManager): allow appending items without overwriting stored lazy items
  packages/@lightningjs/ui-components/src/components/Column/Column.js
  packages/@lightningjs/ui-components/src/components/Column/Column.mdx
  packages/@lightningjs/ui-components/src/components/Column/Column.stories.js
  packages/@lightningjs/ui-components/src/components/FocusManager/FocusManager.js
  packages/@lightningjs/ui-components/src/components/NavigationManager/NavigationManager.js
  packages/@lightningjs/ui-components/src/components/NavigationManager/NavigationManager.mdx
  packages/@lightningjs/ui-components/src/components/Row/Row.js
  packages/@lightningjs/ui-components/src/components/Row/Row.mdx
  packages/@lightningjs/ui-components/src/components/Row/Row.stories.js
Labels: bug

#135 fix(withThemeStyles): add story documentation
  packages/@lightningjs/ui-components/src/docs/ThemingHierarchy.stories.mdx
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/withThemeStyles.mdx
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/withThemeStyles.stories.js
Labels: documentation
