Repository rdkcentral/Lightning-UI-Components, pull requests merged in 2023-09, with the labels that each got.

#354 fix(ScrollWrapper): update ScrollWrapper and ScrollSlider TS declarations
  packages/@lightningjs/ui-components/src/components/ScrollWrapper/ScrollSlider.d.ts
  packages/@lightningjs/ui-components/src/components/ScrollWrapper/ScrollWrapper.d.ts
Labels: refactor

#358 test(Tile): updates test structure into categories
  packages/@lightningjs/ui-components/src/components/Tile/Tile.test.js
  packages/@lightningjs/ui-components/src/components/Tile/__snapshots__/Tile.test.js.snap
Labels: tests

#340 fix(ControlRow): lazy scroll
  packages/@lightningjs/ui-components/src/components/ControlRow/ControlRow.js
  packages/@lightningjs/ui-components/src/components/ControlRow/ControlRow.stories.js
  packages/@lightningjs/ui-components/src/components/Row/Row.js
Labels: bug

#355 feat(Shadow): update shadow TS definiton to latest structure
  packages/@lightningjs/ui-components/src/components/Shadow/Shadow.d.ts
Labels: refactor

#324 fix(TextBox): updates TS structure
  packages/@lightningjs/ui-components/src/components/InlineContent/InlineContent.d.ts
  packages/@lightningjs/ui-components/src/components/TextBox/TextBox.d.ts
Labels: refactor

#347 feat(Keyboard): add updated TS definitions
  packages/@lightningjs/ui-components/src/components/Keyboard/Keyboard.d.ts
  packages/@lightningjs/ui-components/src/components/Keyboard/index.d.ts
  packages/@lightningjs/ui-components/src/components/index.d.ts
Labels: refactor

#348 fix(ControlRow): update TS structure
  packages/@lightningjs/ui-components/src/components/ControlRow/ControlRow.d.ts
  packages/@lightningjs/ui-components/src/components/TitleRow/TitleRow.d.ts
Labels: refactor
