Repository rdkcentral/Lightning-UI-Components, pull requests merged in 2023-08, with the labels that each got.

#303 fix(Badge): update TS structure
  packages/@lightningjs/ui-components/src/components/Badge/Badge.d.ts
  packages/@lightningjs/ui-components/src/components/Badge/Badge.mdx
  packages/@lightningjs/ui-components/src/components/Slider/Slider.d.ts
Labels: refactor

#317 feat: upgrade Lightning version
  packages/@lightningjs/ui-components-test-utils/package.json
  packages/@lightningjs/ui-components/package.json
  packages/apps/lightning-ui-docs/package.json
  yarn.lock
Labels: dependencies

#307 fix(Icon): bug in Icon update
  packages/@lightningjs/ui-components/src/components/Badge/Badge.test.js
  packages/@lightningjs/ui-components/src/components/Badge/__snapshots__/Badge.test.js.snap
  packages/@lightningjs/ui-components/src/components/Checkbox/__snapshots__/Checkbox.test.js.snap
  packages/@lightningjs/ui-components/src/components/Checkbox/__snapshots__/CheckboxSmall.test.js.snap
  packages/@lightningjs/ui-components/src/components/Icon/Icon.js
  packages/@lightningjs/ui-components/src/components/Icon/__snapshots__/Icon.test.js.snap
  packages/@lightningjs/ui-components/src/components/Keyboard/__snapshots__/Keyboard.test.js.snap
  packages/@lightningjs/ui-components/src/components/ListItem/__snapshots__/ListItemSlider.test.js.snap
  packages/@lightningjs/ui-components/src/components/MetadataBase/__snapshots__/MetadataBase.test.js.snap
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/__snapshots__/MetadataCardContent.test.js.snap
  packages/@lightningjs/ui-components/src/components/MetadataTile/__snapshots__/MetadataTile.test.js.snap
  packages/@lightningjs/ui-components/src/components/Provider/__snapshots__/Provider.test.js.snap
  packages/@lightningjs/ui-components/src/components/ScrollWrapper/__snapshots__/ScrollWrapper.test.js.snap
  packages/@lightningjs/ui-components/src/components/Slider/__snapshots__/Slider.test.js.snap
  packages/@lightningjs/ui-components/src/components/Slider/__snapshots__/SliderLarge.test.js.snap
  packages/@lightningjs/ui-components/src/components/TabBar/__snapshots__/Tab.test.js.snap
Labels: bug

#311 fix(label): adds type declarations
  packages/@lightningjs/ui-components/src/components/Label/Label.d.ts
Labels: refactor

#309 feat(Checkbox): update TS structure
  packages/@lightningjs/ui-components/src/components/Checkbox/Checkbox.d.ts
  packages/@lightningjs/ui-components/src/components/Checkbox/Checkbox.mdx
Labels: refactor

#315 fix(Gradient): update TS structure
  packages/@lightningjs/ui-components/src/components/Gradient/Gradient.d.ts
Labels: refactor

#306 fix(TextBox): functionality add to tone property
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/__snapshots__/MetadataCardContent.test.js.snap
  packages/@lightningjs/ui-components/src/components/Provider/__snapshots__/Provider.test.js.snap
  packages/@lightningjs/ui-components/src/components/ScrollWrapper/__snapshots__/ScrollWrapper.test.js.snap
  packages/@lightningjs/ui-components/src/components/TextBox/TextBox.styles.js
  packages/@lightningjs/ui-components/src/components/TextBox/TextBox.test.js
Labels: bug

#302 fix(CardContent): change cardContent doc backgroundColor
  packages/@lightningjs/ui-components/src/components/CardContent/CardContent.mdx
Labels: bug

#320 fix(ProgressBar): update TS structure
  packages/@lightningjs/ui-components/src/components/ProgressBar/ProgressBar.d.ts
  packages/@lightningjs/ui-components/src/components/ProgressBar/ProgressBar.mdx
Labels: refactor

#300 chore: update alpha to theme value
  packages/@lightningjs/ui-components/src/components/Checkbox/Checkbox.styles.js
  packages/@lightningjs/ui-components/src/components/ListItem/ListItem.styles.js
  packages/@lightningjs/ui-components/src/components/Provider/Provider.styles.js
  packages/@lightningjs/ui-components/src/components/Radio/Radio.styles.js
  packages/@lightningjs/ui-components/src/components/ScrollWrapper/__snapshots__/ScrollWrapper.test.js.snap
  packages/@lightningjs/ui-components/src/components/Shadow/Shadow.styles.js
  packages/@lightningjs/ui-components/src/components/Slider/Slider.styles.js
  packages/@lightningjs/ui-components/src/components/Slider/Slider.test.js
  packages/@lightningjs/ui-components/src/components/Slider/SliderLarge.test.js
  packages/@lightningjs/ui-components/src/components/Slider/__snapshots__/Slider.test.js.snap
  packages/@lightningjs/ui-components/src/components/Slider/__snapshots__/SliderLarge.test.js.snap
  packages/@lightningjs/ui-components/src/components/Tile/Tile.styles.js
Labels: enhancement

#318 fix(MetadataBase): updates types declarations
  packages/@lightningjs/ui-components/src/components/MetadataBase/MetadataBase.d.ts
Labels: refactor

#330 feat(Toggle): update TS structure
  packages/@lightningjs/ui-components/src/components/Toggle/Toggle.d.ts
  packages/@lightningjs/ui-components/src/components/Toggle/ToggleSmall.d.ts
Labels: refactor

#327 feat(Tooltip): update TS structure
  packages/@lightningjs/ui-components/src/components/Tooltip/Tooltip.d.ts
  packages/@lightningjs/ui-components/src/components/Tooltip/Tooltip.mdx
Labels: refactor

#328 feat(Knob): update TS structure
  packages/@lightningjs/ui-components/src/components/Knob/Knob.d.ts
Labels: refactor

#326 feat(Input): update TS structure
  packages/@lightningjs/ui-components/src/components/Button/Button.d.ts
  packages/@lightningjs/ui-components/src/components/Input/Input.d.ts
Labels: refactor

#322 feat(GridOverlay): update TS structure
  packages/@lightningjs/ui-components/src/components/GridOverlay/GridOverlay.d.ts
Labels: refactor

#323 feat(Key): update TS structure
  packages/@lightningjs/ui-components/src/components/Key/Key.d.ts
  packages/@lightningjs/ui-components/src/components/Key/Key.mdx
Labels: refactor

#291 fix: refactor withThemeStyles
  .yarn/releases/yarn-3.2.3.cjs
  babel.config.js
  packages/@lightningjs/ui-components-test-utils/src/lng-test-env.js
  packages/@lightningjs/ui-components/babel.config.cjs
  packages/@lightningjs/ui-components/package.json
  packages/@lightningjs/ui-components/src/components/Artwork/Artwork.js
  packages/@lightningjs/ui-components/src/components/Base/Base.js
  packages/@lightningjs/ui-components/src/components/Button/Button.styles.js
  packages/@lightningjs/ui-components/src/components/Card/Card.styles.js
  packages/@lightningjs/ui-components/src/components/Column/Column.test.js
  packages/@lightningjs/ui-components/src/components/ControlRow/__snapshots__/ControlRow.test.js.snap
  packages/@lightningjs/ui-components/src/components/Icon/Icon.js
  packages/@lightningjs/ui-components/src/components/Keyboard/Keyboard.js
  packages/@lightningjs/ui-components/src/components/Keyboard/Keyboard.test.js
  packages/@lightningjs/ui-components/src/components/Keyboard/__snapshots__/Keyboard.test.js.snap
  packages/@lightningjs/ui-components/src/components/Knob/Knob.test.js
  packages/@lightningjs/ui-components/src/components/ProgressBar/ProgressBar.test.js
  packages/@lightningjs/ui-components/src/components/Provider/Provider.js
  packages/@lightningjs/ui-components/src/components/Shadow/Shadow.js
  packages/@lightningjs/ui-components/src/components/Shadow/__snapshots__/Shadow.test.js.snap
  packages/@lightningjs/ui-components/src/components/Slider/Slider.js
  packages/@lightningjs/ui-components/src/components/Surface/Surface.styles.js
  packages/@lightningjs/ui-components/src/components/Surface/Surface.test.js
  packages/@lightningjs/ui-components/src/components/TextBox/TextBox.js
  packages/@lightningjs/ui-components/src/components/TextBox/TextBox.test.js
  packages/@lightningjs/ui-components/src/components/Toggle/Toggle.test.js
  packages/@lightningjs/ui-components/src/docs/utils.js
  packages/@lightningjs/ui-components/src/globals/context/index.js
  packages/@lightningjs/ui-components/src/mixins/withAnnouncer/abbreviations.js
  packages/@lightningjs/ui-components/src/mixins/withAnnouncer/withAnnouncer.test.js
  packages/@lightningjs/ui-components/src/mixins/withEditItems/__snapshots__/withEditItems.test.js.snap
  packages/@lightningjs/ui-components/src/mixins/withExtensions/index.js
  packages/@lightningjs/ui-components/src/mixins/withLayout/index.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/StyleManager.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/cache.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/index.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/styleManager.test.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/themeStyles.test.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/utils.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/utils.test.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/withThemeStyles.stories.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/withThemeStyles.test.js
  packages/@lightningjs/ui-components/src/mixins/withUpdates/index.js
  packages/@lightningjs/ui-components/src/textures/CustomImageTexture.js
  packages/@lightningjs/ui-components/src/utils/index.js
  rollup/babel.config.js
  rollup/rollup.config.js
Labels: refactor

#338 feat(Provider): update TS structure
  packages/@lightningjs/ui-components/src/components/Provider/Provider.d.ts
  packages/@lightningjs/ui-components/src/components/Provider/Provider.mdx
  packages/@lightningjs/ui-components/src/components/Provider/Provider.styles.js
Labels: refactor

#314 fix(Control): update TS structure
  packages/@lightningjs/ui-components/src/components/Button/ButtonSmall.d.ts
  packages/@lightningjs/ui-components/src/components/Control/Control.d.ts
  packages/@lightningjs/ui-components/src/components/Control/ControlSmall.d.ts
  packages/@lightningjs/ui-components/src/components/Control/ControlSmall.styles.js
Labels: refactor

#333 feat(CardContent): update TS structure
  packages/@lightningjs/ui-components/src/components/CardContent/CardContent.d.ts
  packages/@lightningjs/ui-components/src/components/CardContent/CardContent.mdx
  packages/@lightningjs/ui-components/src/components/CardContent/CardContent.styles.js
  packages/@lightningjs/ui-components/src/components/CardContent/CardContentHorizontal.d.ts
  packages/@lightningjs/ui-components/src/components/CardContent/CardContentHorizontalLarge.d.ts
  packages/@lightningjs/ui-components/src/components/CardContent/CardContentVertical.d.ts
  packages/@lightningjs/ui-components/src/components/CardContent/CardContentVerticalSmall.d.ts
  packages/@lightningjs/ui-components/src/components/CardContent/CardContentVerticalSmall.styles.js
  packages/@lightningjs/ui-components/src/components/CardContent/index.d.ts
  packages/@lightningjs/ui-components/src/components/index.d.ts
Labels: refactor

#336 fix(Control): adding height and width to icon control styles
  packages/@lightningjs/ui-components/src/components/Control/Control.js
  packages/@lightningjs/ui-components/src/components/Control/Control.styles.js
Labels: bug

#337 fix(FocusManager): restructuring 'ColumnsWithRows' Story
  packages/@lightningjs/ui-components/src/components/FocusManager/FocusManager.stories.js
Labels: refactor

#310 fix(Tile): update TS structure
  packages/@lightningjs/ui-components/src/components/Tile/Tile.d.ts
  packages/@lightningjs/ui-components/src/components/Tile/Tile.js
Labels: refactor

#342 fix(Column): scrollIndex takes presedence over alwaysScroll
  packages/@lightningjs/ui-components/src/components/Column/Column.js
Labels: bug

#346 feat(MetadataCardContent): update TS declarations
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.d.ts
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.styles.js
  packages/@lightningjs/ui-components/src/components/MetadataTile/MetadataTile.d.ts
Labels: refactor

#319 feat(TextBox): add support for Marquee properties in TextBox
  packages/@lightningjs/ui-components/src/components/TextBox/TextBox.js
Labels: enhancement
