Repository rdkcentral/Lightning-UI-Components, pull requests merged in 2023-12, with the labels that each got.

#419 docs(ListItem): adds parent props to ListItem
  CONTRIBUTING.md
  bin/create.js
  bin/templates/docs.template.js
  bin/templates/export.template.js
  bin/templates/index.js
  bin/templates/story.template.js
  packages/@lightningjs/ui-components/src/components/Button/Button.stories.js
  packages/@lightningjs/ui-components/src/components/Card/Card.stories.js
  packages/@lightningjs/ui-components/src/components/CardContent/CardContent.mdx
  packages/@lightningjs/ui-components/src/components/CardContent/CardContent.stories.js
  packages/@lightningjs/ui-components/src/components/ListItem/ListItem.mdx
  packages/@lightningjs/ui-components/src/components/ListItem/ListItem.stories.js
  packages/@lightningjs/ui-components/src/components/ListItem/ListItemPicker.mdx
  packages/@lightningjs/ui-components/src/components/ListItem/ListItemPicker.stories.js
  packages/@lightningjs/ui-components/src/components/ListItem/ListItemSlider.mdx
  packages/@lightningjs/ui-components/src/components/ListItem/ListItemSlider.stories.js
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.stories.js
  packages/@lightningjs/ui-components/src/components/Slider/Slider.stories.js
  packages/apps/lightning-ui-docs/.storybook/preview.js
Labels: documentation

#418 fix(Storybook): adds docs/story-components to the main index file
  packages/@lightningjs/ui-components/index.js
Labels: bug

#427 fix(withTags): only create tags once per component
  packages/@lightningjs/ui-components/src/mixins/withTags/index.js
Labels: refactor

#428 fix(withThemeStyles): w/h setters don't need to clear style cache
  packages/@lightningjs/ui-components/src/components/ScrollWrapper/ScrollWrapper.js
  packages/@lightningjs/ui-components/src/components/Slider/Slider.js
  packages/@lightningjs/ui-components/src/components/Slider/Slider.test.js
  packages/@lightningjs/ui-components/src/components/TabBar/TabBar.js
  packages/@lightningjs/ui-components/src/components/TabBar/TabBar.test.js
  packages/@lightningjs/ui-components/src/mixins/withThemeStyles/index.js
Labels: refactor
