Repository rdkcentral/Lightning-UI-Components, pull requests merged in 2023-07, with the labels that each got.

#249 docs: add documentation for @lightningjs/ui-test-utils
  packages/@lightningjs/ui-components-test-utils/src/docs/Overview.stories.mdx
  packages/@lightningjs/ui-components-test-utils/src/docs/TestRenderer/create.stories.mdx
  packages/@lightningjs/ui-components-test-utils/src/docs/TestRenderer/toJSON.stories.mdx
  packages/@lightningjs/ui-components-test-utils/src/docs/TestUtils/completeAnimation.stories.mdx
  packages/@lightningjs/ui-components-test-utils/src/docs/TestUtils/fastForward.stories.mdx
  packages/@lightningjs/ui-components-test-utils/src/docs/TestUtils/makeCreateComponent.stories.mdx
  packages/@lightningjs/ui-components-test-utils/src/docs/TestUtils/nextTick.stories.mdx
  packages/@lightningjs/ui-components/src/docs/constants.js
  packages/apps/lightning-ui-docs/.storybook/main.js
Labels: documentation

#246 fix(Tile): re-enabled persistentMetadata and clean up transitions
  packages/@lightningjs/ui-components/src/components/Tile/Tile.js
  packages/@lightningjs/ui-components/src/components/Tile/Tile.test.js
Labels: bug

#258 fix(Slider): removes canvas tags from docs
  packages/@lightningjs/ui-components/src/components/Slider/Slider.mdx
Labels: bug

#298 fix(InlineContent): removes stage.update call from component
  packages/@lightningjs/ui-components/src/components/InlineContent/InlineContent.js
  packages/@lightningjs/ui-components/src/components/NavigationManager/NavigationManager.js
Labels: enhancement

#305 fix(FocusManager): add SignalMap to TypeConfig, update child components
  packages/@lightningjs/ui-components/src/components/Column/Column.d.ts
  packages/@lightningjs/ui-components/src/components/FocusManager/FocusManager.d.ts
  packages/@lightningjs/ui-components/src/components/NavigationManager/NavigationManager.d.ts
  packages/@lightningjs/ui-components/src/components/Row/Row.d.ts
Labels: refactor
