Repository rdkcentral/Lightning-UI-Components, pull requests merged in 2024-01, with the labels that each got.

#451 fix(Slider): adds initial content so Value shows on load
  packages/@lightningjs/ui-components/src/components/Slider/Slider.stories.js
Labels: BUG

#434 fix(Tooltip): adds updateBackground to _update
  packages/@lightningjs/ui-components/src/components/Tooltip/Tooltip.js
  packages/apps/lightning-ui-docs/.storybook/addons/components/ComponentStylesContent.js
  packages/apps/lightning-ui-docs/.storybook/addons/components/ToneRow.js
Labels: BUG

#435 fix(Storybook): updates ResetButton to reset back to theme selected
  packages/apps/lightning-ui-docs/.storybook/addons/components/ResetButton.js
Labels: BUG, STORYBOOK

#450 chore(Storybook): updates Storybook to v 7.6
  packages/apps/lightning-ui-docs/package.json
  yarn.lock
Labels: STORYBOOK

#443 docs(Storybook): updates references of Storybook in docs
  CONTRIBUTING.md
  DEVNOTES.md
  bin/create.js
  bin/templates/component.template.js
  bin/templates/docs.template.js
  bin/templates/story.template.js
  packages/apps/lightning-ui-docs/src/Contributing.mdx
Labels: DOCUMENTATION

#452 feat(MetadataContentCard): Add descriptionDetails TextBox below description in MetadataContentCard
  packages/@lightningjs/ui-components/src/components/CardContent/CardContent.test.js
  packages/@lightningjs/ui-components/src/components/CardContent/CardContentHorizontalLarge.stories.js
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.js
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.mdx
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.stories.js
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.styles.js
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.test.js
  packages/@lightningjs/ui-components/src/components/MetadataCardContent/__snapshots__/MetadataCardContent.test.js.snap
Labels: enhancement
